Controllers/DoAnController.cs
using DoAnCN.Models;
using Firebase.Auth;
using Firebase.Storage;
using FireSharp.Config;
using FireSharp.Interfaces;
using FireSharp.Response;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using PagedList;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace DoAnCN.Controllers
{
    public class DoAnController : Controller
    {
        private static string ApiKey = "AIzaSyDA6iWd1pYuY2pEMVBU-r5Xaq1Pby3M0uU";
        private static string Bucket = "doancn-fb163.appspot.com";
        private static string AuthEmail = "dev.duyson27@gmail.com";
        private static string AuthPassword = "cowphamduyson27";
        IFirebaseConfig config = new FireSharp.Config.FirebaseConfig
        {
            AuthSecret = "NGybKn5jtzUYPIKMZzwUCe67H5y46J16XYUg40FR",
            BasePath = "https://doancn-fb163-default-rtdb.firebaseio.com/",
        };
        IFirebaseClient client;
        // GET: DoAn
        public ActionResult Index(string currentFilter, string searchString, int? page)
        {
            ViewBag.CurrentSort = "";
            ViewBag.CurrentFilter = "";
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;
            //if (!String.IsNullOrEmpty(searchString))
            //{

            //}
            client = new FireSharp.FirebaseClient(config);
            FirebaseResponse response = client.Get("Doans");

            dynamic data = JsonConvert.DeserializeObject<dynamic>(response.Body);
            var list = new List<Doan>();
            foreach (var item in data)
            {
                list.Add(JsonConvert.DeserializeObject<Doan>(((JProperty)item).Value.ToString()));
            }
            list.OrderByDescending(v => v.madoan);

            int pageSize = 10;
            int pageNumber = (page ?? 1);
            IPagedList result = list.ToPagedList(pageNumber, pageSize);
            return View(result);
        }
        
        public ActionResult ChonLoai()
        {
            client = new FireSharp.FirebaseClient(config);
            FirebaseResponse response = client.Get("Loais");

            dynamic data = JsonConvert.DeserializeObject<dynamic>(response.Body);
            var list = new List<Loai>();
            foreach (var item in data)
            {
                list.Add(JsonConvert.DeserializeObject<Loai>(((JProperty)item).Value.ToString()));
            }
            return PartialView(list);

        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Create(Doan doan, HttpPostedFileBase file, string loai)
        {
            var urlhinh = "";
            try
            {
                FileStream stream;
                if (file.ContentLength > 0)
                {
                    string path = Path.Combine(Server.MapPath("~/Images/"), file.FileName);
                    file.SaveAs(path);
                    stream = new FileStream(Path.Combine(path), FileMode.Open);
                    await Task.Run(() => Upload(stream, file.FileName));
                    urlhinh = "gs://doancn-fb163.appspot.com/Images/" + file.FileName;
                    addDoAnToFirebase(doan, urlhinh, loai);
                    ModelState.AddModelError(string.Empty, "Added Successfully");
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
            }

            return View();
        }

        private void addDoAnToFirebase(Doan doan, string urlhinh, string loai)
        {
            
            client = new FireSharp.FirebaseClient(config);
            var data = doan;
            PushResponse response = client.Push("Doans/", data);
            data.madoan = response.Result.name;
            doan.maloai = loai;
            data.anhdoanurl = urlhinh;
            SetResponse setResponse = client.Set("Doans/" + data.madoan, data);
        }


        public async void Upload(FileStream stream, string fileName)
        {
            var auth = new FirebaseAuthProvider(new Firebase.Auth.FirebaseConfig(ApiKey));
            var signin = await auth.SignInWithEmailAndPasswordAsync(AuthEmail, AuthPassword);

            var cancellation = new CancellationTokenSource();

            var task = new FirebaseStorage(
                Bucket,
                new FirebaseStorageOptions
                {
                    AuthTokenAsyncFactory = () => Task.FromResult(signin.FirebaseToken),
                    ThrowOnCancel = true
                }
                ).Child("Images")
                .Child(fileName)
                .PutAsync(stream, cancellation.Token);

            try
            {
                string link = await task;
            }
            catch (Exception ex)
            {
                Console.WriteLine("Lỗi", ex);
            }
        }

        [HttpGet]
        public ActionResult Detail(string id)
        {
            client = new FireSharp.FirebaseClient(config);
            FirebaseResponse response = client.Get("Doans/" + id);
            Doan data = JsonConvert.DeserializeObject<Doan>(response.Body);
            return View(data);
        }

        [HttpGet]
        public ActionResult Edit(string id)
        {
            client = new FireSharp.FirebaseClient(config);
            FirebaseResponse response = client.Get("Doans/" + id);
            Doan data = JsonConvert.DeserializeObject<Doan>(response.Body);
            return View(data);
        }

        [HttpPost]
        public async Task<ActionResult> Edit(Doan doan, HttpPostedFileBase file, string loai)
        {
            var urlhinh = "";
            try
            {
                FileStream stream;
                if (file != null)
                {
                    string path = Path.Combine(Server.MapPath("~/Images/"), file.FileName);
                    file.SaveAs(path);
                    stream = new FileStream(Path.Combine(path), FileMode.Open);
                    await Task.Run(() => Upload(stream, file.FileName));
                    urlhinh = "gs://doancn-fb163.appspot.com/Images/" + file.FileName;
                    client = new FireSharp.FirebaseClient(config);
                    doan.anhdoanurl = urlhinh;
                    doan.maloai = loai;
                    SetResponse response = client.Set("Doans/" + doan.madoan, doan);

                }
                else
                {
                    client = new FireSharp.FirebaseClient(config);
                    doan.maloai = loai;
                    SetResponse response = client.Set("Doans/" + doan.madoan, doan);
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
            }

            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Delete(string id)
        {
            client = new FireSharp.FirebaseClient(config);
            FirebaseResponse response = client.Delete("Doans/" + id);
            return RedirectToAction("Index");
        }
    }
}

Controllers/LoaiController.cs
using DoAnCN.Models;
using FireSharp.Config;
using FireSharp.Interfaces;
using FireSharp.Response;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace LoaiCN.Controllers
{
    public class LoaiController : Controller
    {
        IFirebaseConfig config = new FirebaseConfig
        {
            AuthSecret = "NGybKn5jtzUYPIKMZzwUCe67H5y46J16XYUg40FR",
            BasePath = "https://doancn-fb163-default-rtdb.firebaseio.com/",
        };
        IFirebaseClient client;
        // GET: Food
        public ActionResult Index(string currentFilter, string searchString, int? page)
        {
            ViewBag.CurrentSort = "";
            ViewBag.CurrentFilter = "";
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;
            //if (!String.IsNullOrEmpty(searchString))
            //{

            //}
            client = new FireSharp.FirebaseClient(config);
            FirebaseResponse response = client.Get("Loais");
            
            dynamic data = JsonConvert.DeserializeObject<dynamic>(response.Body);
            var list = new List<Loai>();
            foreach(var item in data)
            {
                list.Add(JsonConvert.DeserializeObject<Loai>(((JProperty)item).Value.ToString()));
            }
            list.OrderByDescending(v => v.maloai);

            int pageSize = 10;
            int pageNumber = (page ?? 1);
            IPagedList result = list.ToPagedList(pageNumber, pageSize);
            return View(result);
            
        }

        public ActionResult MenuLoai()
        {
            client = new FireSharp.FirebaseClient(config);
            FirebaseResponse response = client.Get("Loais");

            dynamic data = JsonConvert.DeserializeObject<dynamic>(response.Body);
            var list = new List<Loai>();
            foreach (var item in data)
            {
                list.Add(JsonConvert.DeserializeObject<Loai>(((JProperty)item).Value.ToString()));
            }
            return PartialView(list);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Loai Loai)
        {
            try
            {
                addLoaiToFirebase(Loai);
                ModelState.AddModelError(string.Empty, "Added Successfully");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
            }
            
            return View();
        }

        private void addLoaiToFirebase(Loai loai)
        {
            client = new FireSharp.FirebaseClient(config);
            var data = loai;
            PushResponse response = client.Push("Loais/", data);
            data.maloai = response.Result.name;
            SetResponse setResponse = client.Set("Loais/" + data.maloai, data);
        }

      

        [HttpGet]
        public ActionResult Detail(string id)
        {
            client = new FireSharp.FirebaseClient(config);
            FirebaseResponse response = client.Get("Loais/"+id);
            Loai data = JsonConvert.DeserializeObject<Loai>(response.Body);
            return View(data);
        }

        [HttpGet]
        public ActionResult Edit(string id)
        {
            client = new FireSharp.FirebaseClient(config);
            FirebaseResponse response = client.Get("Loais/" + id);
            Loai data = JsonConvert.DeserializeObject<Loai>(response.Body);
            return View(data);
        }

        [HttpPost]
        public ActionResult Edit(Loai loai)
        {
            client = new FireSharp.FirebaseClient(config);
            SetResponse response = client.Set("Loais/" + loai.maloai, loai);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Delete(string id)
        {
            client = new FireSharp.FirebaseClient(config);
            FirebaseResponse response = client.Delete("Loais/" + id);
            return RedirectToAction("Index");
        }

    }
}

Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html lang="en" style="overflow-x: hidden">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Dashboard - SB Admin</title>
    <link href="~/Assets/Admin/css/styles.css" rel="stylesheet" />
    <link href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css" rel="stylesheet" crossorigin="anonymous" />

    <link href="~/Assets/Admin/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
          rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="~/Assets/Admin/css/sb-admin-2.min.css" rel="stylesheet">
    <!-- Custom styles for this page -->
    <link href="~/Assets/Admin/vendor/datatables/dataTables.bootstrap4.min.css" rel="stylesheet">


    <script src="https://www.gstatic.com/firebasejs/5.9.1/firebase-app.js">

    </script>
    <script src="https://www.gstatic.com/firebasejs/5.9.1/firebase-storage.js"> </script>
    <!-- Add additional services that you want to use -->
    <script src="https://www.gstatic.com/firebasejs/5.9.1/firebase-auth.js">
    </script>
    <script src="https://www.gstatic.com/firebasejs/5.9.1/firebase-database.js">

    </script>
    <script src="https://www.gstatic.com/firebasejs/5.9.1/firebase-firestore.js">

    </script>
    <script src="https://www.gstatic.com/firebasejs/5.9.1/firebase-messaging.js">

    </script>
    <script src="https://www.gstatic.com/firebasejs/5.9.1/firebase-functions.js">

    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/js/all.min.js" crossorigin="anonymous"></script>

    @RenderSection("script", required: false)
</head>
<body class="sb-nav-fixed">
    <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
        <a class="navbar-brand" href="index.html">Start Bootstrap</a><button class="btn btn-link btn-sm order-1 order-lg-0" id="sidebarToggle" href="#">
            <i class="fas fa-bars"></i>
        </button><!-- Navbar Search-->
        <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
            <div class="input-group">
                <input class="form-control" type="text" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2" />
                <div class="input-group-append">
                    <button class="btn btn-primary" type="button"><i class="fas fa-search"></i></button>
                </div>
            </div>
        </form>
        <!-- Navbar-->
        <ul class="navbar-nav ml-auto ml-md-0">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="userDropdown" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                    <a class="dropdown-item" href="#">Settings</a><a class="dropdown-item" href="#">Activity Log</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="login.html">Logout</a>
                </div>
            </li>
        </ul>
    </nav>
    <div id="layoutSidenav">
        <div id="layoutSidenav_nav">
            <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                <div class="sb-sidenav-menu">
                    <div class="nav">
                        <div class="sb-sidenav-menu-heading">Core</div>
                        <a class="nav-link" href="index.html">
                            <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                            Dashboard
                        </a>
                        <div class="sb-sidenav-menu-heading">Interface</div>
                        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseLayouts" aria-expanded="false" aria-controls="collapseLayouts">
                            <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                            Quản Lý
                            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                        </a>
                        <div class="collapse" id="collapseLayouts" aria-labelledby="headingOne" data-parent="#sidenavAccordion">
                            <nav class="sb-sidenav-menu-nested nav">
                                <a class="nav-link" href="@Url.Action("Index", "NguoiDung")">Người dùng</a>
                                <a class="nav-link" href="@Url.Action("Index", "Loai")">Loại đồ ăn</a>
                                <a class="nav-link" href="@Url.Action("Index", "DoAn")">Đồ ăn</a>
                            </nav>
                        </div>
                        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages" aria-expanded="false" aria-controls="collapsePages">
                            <div class="sb-nav-link-icon"><i class="fas fa-book-open"></i></div>
                            Pages
                            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                        </a>
                        <div class="collapse" id="collapsePages" aria-labelledby="headingTwo" data-parent="#sidenavAccordion">
                            <nav class="sb-sidenav-menu-nested nav accordion" id="sidenavAccordionPages">
                                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#pagesCollapseAuth" aria-expanded="false" aria-controls="pagesCollapseAuth">
                                    Authentication
                                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                                </a>
                                <div class="collapse" id="pagesCollapseAuth" aria-labelledby="headingOne" data-parent="#sidenavAccordionPages">
                                    <nav class="sb-sidenav-menu-nested nav"><a class="nav-link" href="login.html">Login</a><a class="nav-link" href="register.html">Register</a><a class="nav-link" href="password.html">Forgot Password</a></nav>
                                </div>
                                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#pagesCollapseError" aria-expanded="false" aria-controls="pagesCollapseError">
                                    Error
                                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                                </a>
                                <div class="collapse" id="pagesCollapseError" aria-labelledby="headingOne" data-parent="#sidenavAccordionPages">
                                    <nav class="sb-sidenav-menu-nested nav"><a class="nav-link" href="401.html">401 Page</a><a class="nav-link" href="404.html">404 Page</a><a class="nav-link" href="500.html">500 Page</a></nav>
                                </div>
                            </nav>
                        </div>
                        <div class="sb-sidenav-menu-heading">Addons</div>
                        <a class="nav-link" href="charts.html">
                            <div class="sb-nav-link-icon"><i class="fas fa-chart-area"></i></div>
                            Charts
                        </a><a class="nav-link" href="tables.html">
                            <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
                            Bảng
                        </a>
                    </div>
                </div>
                <div class="sb-sidenav-footer">
                    <div class="small">Logged in as:</div>
                    Start Bootstrap
                </div>
            </nav>
        </div>
        <div id="layoutSidenav_content">
            <main style="padding: 20px">
                @RenderBody()
            </main>
            <footer class="py-4 bg-light mt-auto">
                <div class="container-fluid">
                    <div class="d-flex align-items-center justify-content-between small">
                        <div class="text-muted">Copyright &copy; Your Website 2019</div>
                        <div>
                            <a href="#">Privacy Policy</a>
                            &middot;
                            <a href="#">Terms &amp; Conditions</a>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    </div>
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    <script src="~/Assets/Admin/vendor/jquery/jquery.min.js"></script>
    <script src="~/Assets/Admin/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- Core plugin JavaScript-->
    <script src="~/Assets/Admin/vendor/jquery-easing/jquery.easing.min.js"></script>
    <!-- Custom scripts for all pages-->
    <script src="~/Assets/Admin/js/sb-admin-2.min.js"></script>
    <!-- Page level plugins -->
    <script src="~/Assets/Admin/vendor/datatables/jquery.dataTables.min.js"></script>
    <script src="~/Assets/Admin/vendor/datatables/dataTables.bootstrap4.min.js"></script>
    <!-- Page level custom scripts -->
    <script src="~/Assets/Admin/js/demo/datatables-demo.js"></script>

    @*<script src="https://code.jquery.com/jquery-3.4.1.min.js" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>*@
    <script src="~/Assets/Admin/js/scripts.js"></script>
    @*<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>*@
    <script src="~/Assets/Admin/assets/demo/chart-area-demo.js"></script>
    <script src="~/Assets/Admin/assets/demo/chart-bar-demo.js"></script>
    @*<script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js" crossorigin="anonymous"></script>*@
    <script src="~/ckfinder/ckfinder.js"></script>
    <script src="~/Assets/Admin/assets/demo/datatables-demo.js"></script>
    @RenderSection("scripthinh", required: false)
</body>
</html>