Models/Loai.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace DoAnCN.Models
{
    public class Loai
    {
        public string maloai { get; set; }
        public string tenloai { get; set; }
    }
}

Controllers/LoaiController.cs
using DoAnCN.Models;
using FireSharp.Config;
using FireSharp.Interfaces;
using FireSharp.Response;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace LoaiCN.Controllers
{
    public class LoaiController : Controller
    {
        IFirebaseConfig config = new FirebaseConfig
        {
            AuthSecret = "NGybKn5jtzUYPIKMZzwUCe67H5y46J16XYUg40FR",
            BasePath = "https://doancn-fb163-default-rtdb.firebaseio.com/",
        };
        IFirebaseClient client;
        // GET: Food
        public ActionResult Index(string currentFilter, string searchString, int? page)
        {
            ViewBag.CurrentSort = "";
            ViewBag.CurrentFilter = "";
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;
            //if (!String.IsNullOrEmpty(searchString))
            //{

            //}
            client = new FireSharp.FirebaseClient(config);
            FirebaseResponse response = client.Get("Loais");
            
            dynamic data = JsonConvert.DeserializeObject<dynamic>(response.Body);
            var list = new List<Loai>();
            foreach(var item in data)
            {
                list.Add(JsonConvert.DeserializeObject<Loai>(((JProperty)item).Value.ToString()));
            }
            list.OrderByDescending(v => v.maloai);

            int pageSize = 10;
            int pageNumber = (page ?? 1);
            IPagedList result = list.ToPagedList(pageNumber, pageSize);
            return View(result);
            
        }

        public ActionResult MenuLoai()
        {
            client = new FireSharp.FirebaseClient(config);
            FirebaseResponse response = client.Get("Loais");

            dynamic data = JsonConvert.DeserializeObject<dynamic>(response.Body);
            var list = new List<Loai>();
            foreach (var item in data)
            {
                list.Add(JsonConvert.DeserializeObject<Loai>(((JProperty)item).Value.ToString()));
            }
            return PartialView(list);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Loai Loai)
        {
            try
            {
                addLoaiToFirebase(Loai);
                ModelState.AddModelError(string.Empty, "Added Successfully");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
            }
            
            return View();
        }

        private void addLoaiToFirebase(Loai loai)
        {
            client = new FireSharp.FirebaseClient(config);
            var data = loai;
            PushResponse response = client.Push("Loais/", data);
            data.maloai = response.Result.name;
            SetResponse setResponse = client.Set("Loais/" + data.maloai, data);
        }

      

        [HttpGet]
        public ActionResult Detail(string id)
        {
            client = new FireSharp.FirebaseClient(config);
            FirebaseResponse response = client.Get("Loais/"+id);
            Loai data = JsonConvert.DeserializeObject<Loai>(response.Body);
            return View(data);
        }

        [HttpGet]
        public ActionResult Edit(string id)
        {
            client = new FireSharp.FirebaseClient(config);
            FirebaseResponse response = client.Get("Loais/" + id);
            Loai data = JsonConvert.DeserializeObject<Loai>(response.Body);
            return View(data);
        }

        [HttpPost]
        public ActionResult Edit(Loai loai)
        {
            client = new FireSharp.FirebaseClient(config);
            SetResponse response = client.Set("Loais/" + loai.maloai, loai);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Delete(string id)
        {
            client = new FireSharp.FirebaseClient(config);
            FirebaseResponse response = client.Delete("Loais/" + id);
            return RedirectToAction("Index");
        }

    }
}

Controllers/NguoiDungController.cs
using DoAnCN.Common;
using DoAnCN.Models;
using FireSharp.Config;
using FireSharp.Interfaces;
using FireSharp.Response;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DoAnCN.Controllers
{
    public class NguoiDungController : Controller
    {
        IFirebaseConfig config = new FirebaseConfig
        {
            AuthSecret = "NGybKn5jtzUYPIKMZzwUCe67H5y46J16XYUg40FR",
            BasePath = "https://doancn-fb163-default-rtdb.firebaseio.com/",
        };
        IFirebaseClient client;
        // GET: NguoiDung
        public ActionResult Index(string currentFilter, string searchString, int? page)
        {
            ViewBag.CurrentSort = "";
            ViewBag.CurrentFilter = "";
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;
            //if (!String.IsNullOrEmpty(searchString))
            //{

            //}
            client = new FireSharp.FirebaseClient(config);
            FirebaseResponse response = client.Get("Nguoidungs");

            dynamic data = JsonConvert.DeserializeObject<dynamic>(response.Body);
            var list = new List<Nguoidung>();
            foreach (var item in data)
            {
                list.Add(JsonConvert.DeserializeObject<Nguoidung>(((JProperty)item).Value.ToString()));
            }
            list.OrderByDescending(v => v.makh);

            int pageSize = 10;
            int pageNumber = (page ?? 1);
            IPagedList result = list.ToPagedList(pageNumber, pageSize);
            return View(result);
            
        }
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Nguoidung nguoidung)
        {
            try
            {
                addNguoiDungToFirebase(nguoidung);
                ModelState.AddModelError(string.Empty, "Added Successfully");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
            }

            return View();
        }

        private void addNguoiDungToFirebase(Nguoidung nguoidung)
        {
            client = new FireSharp.FirebaseClient(config);
            var data = nguoidung;
            PushResponse response = client.Push("Nguoidungs/", data);
            data.makh = response.Result.name;
            SetResponse setResponse = client.Set("Nguoidungs/" + data.makh, data);
        }

        [HttpGet]
        public ActionResult Detail(string id)
        {
            client = new FireSharp.FirebaseClient(config);
            FirebaseResponse response = client.Get("Nguoidungs/" + id);
            Nguoidung data = JsonConvert.DeserializeObject<Nguoidung>(response.Body);
            return View(data);
        }

        [HttpGet]
        public ActionResult Edit(string id)
        {
            client = new FireSharp.FirebaseClient(config);
            FirebaseResponse response = client.Get("Nguoidungs/" + id);
            Nguoidung data = JsonConvert.DeserializeObject<Nguoidung>(response.Body);
            return View(data);
        }

        [HttpPost]
        public ActionResult Edit(Nguoidung nguoidung)
        {
            client = new FireSharp.FirebaseClient(config);
            SetResponse response = client.Set("Nguoidungs/" + nguoidung.makh, nguoidung);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Delete(string id)
        {
            client = new FireSharp.FirebaseClient(config);
            FirebaseResponse response = client.Delete("Nguoidungs/" + id);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult DangKy()
        {
            return View();
        }

        [HttpPost]
        public ActionResult DangKy(Nguoidung nguoidung)
        {
            try
            {
                addNguoiDungToFirebase(nguoidung);
                ModelState.AddModelError(string.Empty, "Đăng ký thành công !");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
            }
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult DangNhap()
        {
            if (Session["USER_SESSION"] != null) return RedirectToAction("Index", new { controller = "Home" });
            return View();
        }

        [HttpPost]
        public ActionResult DangNhap(LoginModel nguoidung)
        {
            try
            {
                client = new FireSharp.FirebaseClient(config);
                FirebaseResponse response = client.Get("Nguoidungs");

                dynamic data = JsonConvert.DeserializeObject<dynamic>(response.Body);
                var list = new List<Nguoidung>();
                foreach (var item in data)
                {
                    list.Add(JsonConvert.DeserializeObject<Nguoidung>(((JProperty)item).Value.ToString()));
                }
                foreach (var account in list)
                {
                    if (nguoidung.Username == account.taikhoan && nguoidung.Password == account.matkhau)
                    {
                        var userSession = new UserLogin();
                        userSession.UserName = account.taikhoan;
                        userSession.UserID = account.makh;
                        Session.Add(CommonConstants.USER_SESSION, userSession);
                        ModelState.AddModelError(string.Empty, "Đăng ký thành công !");
                        //if (data.taikhoan.Contains("admin")) return RedirectToAction("Index", "Admin");
                        return RedirectToAction("Index", "Home");
                    }
                   
                }
                
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
            }
            return RedirectToAction("Index");
        }
        
        public ActionResult LoginStatus()
        {
            ViewBag.Status = 0;
            ViewBag.Ten = "Quý khách chưa đăng nhập";
            ViewBag.Anh = "";
            var user = (UserLogin)Session[CommonConstants.USER_SESSION];
            if (user != null)
            {
                ViewBag.Status = 1;
                ViewBag.Ten = user.UserName;
            }
            return PartialView();
        }
        public ActionResult DangXuat()
        {
            Session[CommonConstants.USER_SESSION] = null;
            return Redirect("/");
        }
    }
}

Views/Loai/Create.cshtml
@model DoAnCN.Models.Loai

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Loai</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        

        <div class="form-group">
            @Html.LabelFor(model => model.tenloai, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.tenloai, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.tenloai, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Views/Loai/Detail.cshtml
@model DoAnCN.Models.Loai

@{
    ViewBag.Title = "Detail";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Chi tiết Loại</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.maloai)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.maloai)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tenloai)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tenloai)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.maloai }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Views/Loai/Edit.cshtml
@model DoAnCN.Models.Loai

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Loai</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.maloai, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.maloai, new { htmlAttributes = new { @class = "form-control disabled" } })
                @Html.ValidationMessageFor(model => model.maloai, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.tenloai, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.tenloai, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.tenloai, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Views/Loai/Index.cshtml
@*@model IEnumerable<DoAnCN.Models.Loai>

    @{
        ViewBag.Title = "Index";
        Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
    }

    <h2>Index</h2>

    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.maloai)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.tenloai)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.maloai)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.tenloai)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                    @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                    @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
                </td>
            </tr>
        }

    </table>*@



@using PagedList.Mvc;
@using DoAnCN.Models;

@model  PagedList.PagedList<Loai>

<link href=”~/Content/PagedList.css” rel=”stylesheet” type=”text/css” />
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<style>
    .paginate_button > a {
        z-index: 3;
        color: #fff;
        background-color: #4e73df;
        border-color: #4e73df;
    }
</style>
<p>
    @Html.ActionLink("Tạo mới loại đồ ăn", "Create")
</p>
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">LOẠI ĐỒ ĂN</h6>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>Mã Loại</th>
                        <th>Tên Loại</th>
                        <th>...</th>
                    </tr>
                </thead>
                <tfoot>
                    <tr>
                        <th>Mã Loại</th>
                        <th>Tên Loại</th>
                        <th>...</th>
                    </tr>
                </tfoot>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.maloai)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.tenloai)
                            </td>
                            <td>
                                @Html.ActionLink("Edit", "Edit", new { id = item.maloai }) |
                                @Html.ActionLink("Details", "Detail", new { id = item.maloai }) |
                                @Ajax.ActionLink("Delete",
                                               "Delete",
                                               "Loai",
                                               new { id = item.maloai },
                                               new AjaxOptions {
                                                   HttpMethod = "POST",
                                                   Confirm = "Bạn có muốn xóa " + item.tenloai,
                                                   OnSuccess = "RemoveRow"
                                               },
                                               new { @class = "pest_btn" })
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("Index", new { page = page }),
            new PagedListRenderOptions
            {
                LiElementClasses = new string[] { "page-item paginate_button" },
                LinkToNextPageFormat = "<i class='fas fa-angle-right'></i>",
                LinkToLastPageFormat = "<i class='fad fa-angle-double-right'></i>",
                LinkToPreviousPageFormat = "<i class='fas fa-angle-left'></i>",
                LinkToFirstPageFormat = "<i class='fad fa-angle-double-left'></i>"
                //PageClasses = new string[] { "page-link" }
            }

   )


<script type="text/javascript">
    function RemoveRow() {
        var $tr = $(this).closest('tr');
        $tr.remove();
    }
</script>

Views/Loai/MenuLoai.cshtml
@model IEnumerable<DoAnCN.Models.Loai>
@foreach (var loai in Model)
{
    <li><a href="@Url.Action("Index", "NguoiDung", new { id = loai.maloai })">@loai.tenloai</a></li>
}